import { useEffect, useState } from 'react';
export default function Header({ profile, profileKey, hasProjects, onToggle, effects, onEffectsToggle, active, onNavigate }) {
  const [open, setOpen] = useState(false);
  useEffect(() => { const escape = event => { if (event.key === 'Escape') { setOpen(false); document.querySelector('#menu-toggle')?.focus(); } }; if (open) addEventListener('keydown', escape); return () => removeEventListener('keydown', escape); }, [open]);
  function navigate(event, id) { event.preventDefault(); setOpen(false); onNavigate(id); }
  const links = [['home', 'Accueil'], ['profile', 'Profil'], ...(hasProjects ? [['portfolio', 'Portfolio']] : []), ['contact', 'Contact']];
  const currentGroup = ['skills','experience','training'].includes(active) ? 'profile' : active;
  return <header className="header"><a className="brand" href="#home" onClick={e => navigate(e, 'home')} aria-label="Nathan Lachery — accueil">NL<span>.</span></a><nav id="navigation" className={open ? 'is-open' : ''} aria-label="Navigation principale">{links.map(([id, label]) => <a key={id} href={`#${id}`} onClick={e => navigate(e, id)} aria-current={currentGroup === id ? 'location' : undefined}>{label}</a>)}</nav><div className="header-actions"><button className="fx-toggle" onClick={onEffectsToggle} aria-pressed={effects === 'full'} aria-label={`FX : animations ${effects === 'full' ? 'activées. Réduire les animations' : 'réduites. Activer les animations'}`} title="Activer ou réduire les animations">FX <span aria-hidden="true">{effects === 'full' ? '●' : '○'}</span></button><button id="profile-toggle" className="profile-toggle" onClick={() => { setOpen(false); onToggle(); }} aria-label={`Profil ${profile.label} actif. Passer au profil ${profileKey === 'dev' ? 'Industrie' : 'Dev'}`}><span id="toggle-icon" aria-hidden="true">{profile.icon}</span><span>{profile.label}</span><span className="toggle-arrows" aria-hidden="true">⇄</span></button><button id="menu-toggle" className="menu-toggle" aria-label={open ? 'Fermer le menu' : 'Ouvrir le menu'} aria-expanded={open} aria-controls="navigation" onClick={() => setOpen(!open)}><span/><span/></button></div><div className="header-progress" aria-hidden="true"><span id="progress"/></div></header>;
}
